# Sklearn

## sklearn.model_selection

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
import pandas as pd
import numpy as np
from sklearn import model_selection, datasets

import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy.stats as sts
import seaborn as sns

sns.set()
sns.set_style("whitegrid")

%matplotlib inline

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [4]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [5]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [6]:
print ('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [7]:
print('Обучающая выборка:\n', train_data[:5])
print('\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[5.  3.5 1.6 0.6]
 [5.2 3.5 1.5 0.2]
 [6.4 2.7 5.3 1.9]
 [6.6 3.  4.4 1.4]
 [5.8 2.7 5.1 1.9]]


Тестовая выборка:
 [[6.6 2.9 4.6 1.3]
 [5.8 4.  1.2 0.2]
 [6.4 2.9 4.3 1.3]
 [5.6 3.  4.1 1.3]
 [5.4 3.7 1.5 0.2]]


In [8]:
print('Метки классов на обучающей выборке:\n', train_labels)
print('\n')
print('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [0 0 2 1 2 2 2 2 1 2 0 1 0 0 2 0 0 1 1 0 2 2 0 0 1 2 1 0 2 0 0 1 2 1 2 0 1
 0 2 2 2 1 0 1 1 0 1 2 1 1 2 1 2 0 1 0 1 0 1 2 2 2 1 2 2 1 2 0 0 2 1 1 1 1
 1 1 2 0 1 2 1 2 1 2 0 0 0 2 1 2 2 1 2 0 0 0 0 2 2 0 1 2 2 0 1]


Метки классов на тестовой выборке:
 [1 0 1 1 0 0 2 1 2 0 1 1 2 0 2 2 1 1 2 0 1 0 2 0 1 1 0 2 0 0 0 0 0 0 2 2 1
 0 0 0 1 2 1 1 2]


### Стратегии проведения кросс-валидации

In [9]:
#сгенерируем короткое подобие датасета, где элементы совпадают с порядковым номером
X = range(0,10)

#### KFold

In [16]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [17]:
kf = model_selection.KFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[0 2 3 4 9] [1 5 6 7 8]
[1 5 6 7 8] [0 2 3 4 9]


In [18]:
kf = model_selection.KFold(n_splits = 2, shuffle = True, random_state = 1)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [19]:
y = np.array([0] * 5 + [1] * 5)
print(y)

skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [20]:
target = np.array([0, 1] * 5)
print(target)

skf = model_selection.StratifiedKFold(n_splits = 2,shuffle = True)
for train_indices, test_indices in skf.split(X, target):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[3 4 6 7] [0 1 2 5 8 9]
[0 1 2 5 8 9] [3 4 6 7]


#### ShuffleSplit

In [21]:
ss = model_selection.ShuffleSplit(n_splits = 10, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
    print(train_indices, test_indices)

[1 7 5 4 8 9 0 6] [2 3]
[6 9 0 1 4 2 5 3] [7 8]
[1 5 2 0 6 9 7 3] [4 8]
[5 3 1 6 2 9 8 7] [4 0]
[5 9 2 6 4 8 1 3] [0 7]
[5 3 8 2 1 7 6 0] [4 9]
[6 0 1 2 3 5 9 8] [4 7]
[9 6 1 0 2 7 4 5] [8 3]
[4 8 5 9 7 1 6 0] [2 3]
[9 1 6 8 3 5 2 0] [7 4]


#### StratifiedShuffleSplit

In [22]:
target = np.array([0] * 5 + [1] * 5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 0 7 2 1 9 5 8] [6 4]
[1 4 6 3 5 0 7 8] [2 9]
[5 6 2 3 4 8 1 7] [0 9]
[4 3 8 1 9 2 5 6] [0 7]


#### Leave-One-Out

In [ ]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators